### ISSUE TITLE
你好作者，有适配最新版本rn的想法吗

### ISSUE THREAD

**Issue by liguanhan** [songxiaoliang/react-native-baidu-face#11]

**Comment by songxiaoliang** [comment]
@liguanhan 嗯, 有这个打算, 但是一时半会搞不定, 非常希望大家能加进来共同维护

**Comment by liguanhan** [comment]
谢谢作者，作者我刚才集成的时候报了这个错，是那里出了问题吗？
![image](https://user-images.githubusercontent.com/24800090/78872886-8559a700-7a7c-11ea-9125-0a3f4597f553.png)
![image](https://user-images.githubusercontent.com/24800090/78872964-a4f0cf80-7a7c-11ea-86fe-0730c39d0cce.png)

**Comment by songxiaoliang** [comment]
@liguanhan 是缺少AppTheme, 你参考下READEMEREADEME配置
