### ISSUE TITLE
你好作者，人脸采集模块集成后，如何弄人脸识别模块呢？有例子吗？

### ISSUE THREAD

**Issue by liguanhan** [songxiaoliang/react-native-baidu-face#12]
你好作者，人脸采集模块集成后，如何弄人脸识别模块呢？有例子吗？
![image](https://user-images.githubusercontent.com/24800090/79197665-b7944b80-7e64-11ea-8251-f99ebf065523.png)
ling'w

采集之后的模块如何保存在本地呢，是我们自己本地保存图片，还是用百度的离线图片库呢？

**Comment by liguanhan** [comment]
![image](https://user-images.githubusercontent.com/24800090/79197833-080ba900-7e65-11ea-846e-6b426647f13e.png)

**Comment by liguanhan** [comment]
人脸识别模块基于Native层进行封装，即要从Native层进行配置。关于配置的详细流程可以参考百度人脸识别SDK官方文档：

这个有提示和例子参考吗作者

**Comment by songxiaoliang** [comment]
@liguanhan 这个还是要去官方文档看下的

**Comment by liguanhan** [comment]
作者你有把人脸识别模块集成进去吗，里面的配置流程照百度官网和react-native官网的与原生通信就差不多了吧，作者你有提示和经验吗
目前其实我已经集成了人脸采集和识别进去了吧，不需要再去集成人脸识别

**Comment by songxiaoliang** [comment]
@liguanhan 是的, 集成一个即可

**Comment by liguanhan** [comment]
@songxiaoliang 谢谢作者了，那我现在照着react-native官网的与原生模块通信文档就可以把人脸识别的东西也一起弄了吧

人脸采集后的照片放到本地离线库里怎么操作呢

**Comment by songxiaoliang** [comment]
@liguanhan 其实就是几张图片, 本地存储就可以

**Comment by liguanhan** [comment]
@songxiaoliang 作者，如果有很多张图片呢，怎么和百度的离线人脸库弄到一起

另外人脸识别的对比部分有点技术难题，你那里有人脸识别的识别对比部分的代码吗，提示一下

**Comment by liguanhan** [comment]
@songxiaoliang sendFaceCheckBase64Img和getName这两个方法怎么使用呢？

**Comment by liguanhan** [comment]
/**
     * 获取检测图片结果（Base64），传递到react native
     */
    public void sendFaceCheckBase64Img(WritableMap faceCheckResult) {
        mContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit(GET_RESULT_EVENT, faceCheckResult);
    }

作者你好，这个在react-native如何接收呢，我用了DeviceEventEmitter没接到，有代码案例吗

**Comment by liguanhan** [comment]
作者你好，faceCheckCallback这个方法我这里没有响应

**Comment by liguanhan** [comment]
作者你好，faceCheckCallback这个方法没有响应，知道是什么原因吗

**Comment by songxiaoliang** [comment]
@liguanhan 人脸图像活体检测采集完成后, 会触发 faceCheckCallback 方法, 你在RN层可以拿到对应的数据

**Comment by liguanhan** [comment]
@songxiaoliang 兄弟，怎么让人脸离线图像识别采集faceDetectExp后获得响应数据呢，这个我比较需要，谢谢兄弟了，可以加微信吗，我的是lgh1141968878有偿
