### ISSUE TITLE
Use of undeclared identifier 'IDLFaceLivenessManager'

### ISSUE THREAD

**Issue by Icacls** [songxiaoliang/react-native-baidu-face#3]
iOS集成Face SDK  已经引入SDK 但是build的时候一直报错 Use of undeclared identifier 'IDLFaceLivenessManager' 错误信息截图如下

![image](https://user-images.githubusercontent.com/3806467/51299574-ebb36d80-1a63-11e9-8dc0-969de40c95f2.png)

能帮看看是哪里出了问题么

**Comment by yuezonglun** [comment]
我也遇到这样的问题，你说怎么解决的啊
